name: Multi-Job-Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
    - opened
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "Hello my name is ${{ vars.MY_NAME }}

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Test Step
        run: echo "This is test step"

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Deploy Job
        run: echo "Deployin applocation"
        
